services:
  holbegram:
    build: .
    volumes:
      - .:/holbegram
      - flutter-data:/usr/local/flutter
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0
    working_dir: /holbegram

volumes:
  flutter-data: