// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgu0Xw50JA9Sw1htUCfZ97qurJIjio3-0',
    appId: '1:341419502242:web:597684fd43195ecfbf85fb',
    messagingSenderId: '341419502242',
    projectId: 'holbegram-8c6fa',
    authDomain: 'holbegram-8c6fa.firebaseapp.com',
    storageBucket: 'holbegram-8c6fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jNttSYaNmgorwdM_7-1osOksoVivVkM',
    appId: '1:341419502242:android:78f145472a9b1bdcbf85fb',
    messagingSenderId: '341419502242',
    projectId: 'holbegram-8c6fa',
    storageBucket: 'holbegram-8c6fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8XvTtU70ggrcwpgIMf3c9Ut2Zqgp6-2A',
    appId: '1:341419502242:ios:1586884c61280537bf85fb',
    messagingSenderId: '341419502242',
    projectId: 'holbegram-8c6fa',
    storageBucket: 'holbegram-8c6fa.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8XvTtU70ggrcwpgIMf3c9Ut2Zqgp6-2A',
    appId: '1:341419502242:ios:1586884c61280537bf85fb',
    messagingSenderId: '341419502242',
    projectId: 'holbegram-8c6fa',
    storageBucket: 'holbegram-8c6fa.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgu0Xw50JA9Sw1htUCfZ97qurJIjio3-0',
    appId: '1:341419502242:web:3a2100e7891f98f0bf85fb',
    messagingSenderId: '341419502242',
    projectId: 'holbegram-8c6fa',
    authDomain: 'holbegram-8c6fa.firebaseapp.com',
    storageBucket: 'holbegram-8c6fa.firebasestorage.app',
  );
}
